# Generated by Django 5.0.6 on 2024-08-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ben', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='city',
            new_name='ville',
        ),
    ]
