# Generated by Django 5.0.6 on 2024-08-13 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ben', '0002_rename_city_customer_ville'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prix_Achat',
            new_name='prix_achat',
        ),
    ]
