# Generated by Django 4.1.13 on 2024-08-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ben', '0004_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
